import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const futura = localFont({
  src: [
    {
      path: './fonts/Futura-Medium-01.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Futura-MediumItalic-02.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/Futura-Bold-03.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${futura.className} overflow-hidden bg-stone-50 text-neutral-700`}
      >
        {children}
      </body>
    </html>
  )
}
